// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSSFAfb9dftw7wns3VCboQE2e_pTK6fSA',
    appId: '1:590908768684:web:fc3c9492b84074f4497a09',
    messagingSenderId: '590908768684',
    projectId: 'lotn-commonwealth-app',
    authDomain: 'lotn-commonwealth-app.firebaseapp.com',
    storageBucket: 'lotn-commonwealth-app.firebasestorage.app',
    measurementId: 'G-0GX1CY0FP1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLi7TTU0KqHreSzmQC69u2JZw1tglPmZ4',
    appId: '1:590908768684:android:dfbe834a6e8fb248497a09',
    messagingSenderId: '590908768684',
    projectId: 'lotn-commonwealth-app',
    storageBucket: 'lotn-commonwealth-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMxWYkMGMN5WXbOiclaa9jeQQireRbDKE',
    appId: '1:590908768684:ios:ed0d740bb2a4c09d497a09',
    messagingSenderId: '590908768684',
    projectId: 'lotn-commonwealth-app',
    storageBucket: 'lotn-commonwealth-app.firebasestorage.app',
    iosBundleId: 'com.example.lotnApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMxWYkMGMN5WXbOiclaa9jeQQireRbDKE',
    appId: '1:590908768684:ios:ed0d740bb2a4c09d497a09',
    messagingSenderId: '590908768684',
    projectId: 'lotn-commonwealth-app',
    storageBucket: 'lotn-commonwealth-app.firebasestorage.app',
    iosBundleId: 'com.example.lotnApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSSFAfb9dftw7wns3VCboQE2e_pTK6fSA',
    appId: '1:590908768684:web:a30a415b55e8a81c497a09',
    messagingSenderId: '590908768684',
    projectId: 'lotn-commonwealth-app',
    authDomain: 'lotn-commonwealth-app.firebaseapp.com',
    storageBucket: 'lotn-commonwealth-app.firebasestorage.app',
    measurementId: 'G-FLLT4C8MLY',
  );
}
